version: '3.8'
services:
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      OKTA_OAUTH0_ISSUER: ${OKTA_OAUTH0_ISSUER}
      OKTA_OAUTH0_AUDIENCE: ${OKTA_OAUTH0_AUDIENCE}
      OKTA_OAUTH0_CLIENT_ID: ${OKTA_OAUTH0_CLIENT_ID}
      OKTA_OAUTH0_CLIENT_SECRET: ${OKTA_OAUTH0_CLIENT_SECRET}
    depends_on:
      - db

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "3000:80"

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
